### ISSUE TITLE
Add pressure drop 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#11]
Remove assumption of constant pressure

**Comment by savreline** [comment]
@nagimov Should we use something like `Delta P = K * m^2 / rho` for the pressure drop?

**Comment by savreline** [comment]
@nagimov Plots for the pressure drop. As expected, He pressure (red) is decreasing and N2 pressure (blue) is increasing. Input He pressure is 1.25 atm and 1.75 atm for N2.

Not sure what is going on in the beginning, will study that.  

![plot_p20](https://cloud.githubusercontent.com/assets/21995425/19403258/bc1aa2c4-921a-11e6-809e-fa525b42a9de.png)
![plot_delta_p20](https://cloud.githubusercontent.com/assets/21995425/19403252/b5fdb3ea-921a-11e6-8260-df71aaed4b78.png)

**Comment by savreline** [comment]
68 second solution time on a `20x20x20` grid, with everything accounted for.

**Comment by savreline** [comment]
![plot_delta_p20](https://cloud.githubusercontent.com/assets/21995425/19498546/583d6df2-9546-11e6-9af7-923f1bbc49fa.png)

![plot_p20](https://cloud.githubusercontent.com/assets/21995425/19498544/55e0e3e0-9546-11e6-844e-869c810f33af.png)

**Comment by savreline** [comment]
Low temperature solution

![plot_he20](https://cloud.githubusercontent.com/assets/21995425/19540667/f029b56a-9615-11e6-95e5-7efe012ff70c.png)
![plot_n220](https://cloud.githubusercontent.com/assets/21995425/19540668/f2cc7500-9615-11e6-8c81-d48e263f6ac4.png)
![plot_overall20](https://cloud.githubusercontent.com/assets/21995425/19540669/f7ea95da-9615-11e6-8d37-8dfedc52f2fd.png)
![plot_wall20](https://cloud.githubusercontent.com/assets/21995425/19540673/fae21d80-9615-11e6-94f7-003743d9f319.png)

**Comment by nagimov** [comment]
done, closing
