### ISSUE TITLE
Add wall between HX streams 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#12]

**Comment by savreline** [comment]
@nagimov Plots for the model with the wall. 20 time steps, 10 slices, took over 20 min to solve. Look OK I guess. I lower HX_UA a little bit, otherwise plots get too close and solution is not as good. 

<img src="https://cloud.githubusercontent.com/assets/21995425/19002418/c9c2ad06-8700-11e6-8c85-09e37eff06ec.png" width=250px> <img src="https://cloud.githubusercontent.com/assets/21995425/19002419/c9c3c2c2-8700-11e6-8877-f448de7e7aa7.png" width=250px> <img src="https://cloud.githubusercontent.com/assets/21995425/19002417/c9c102da-8700-11e6-80f1-ef0a701b532e.png" width=250px>

**Comment by savreline** [comment]
@nagimov With much higher `HX_UA=1e4`, 20 time steps, 10 slices. 

![plot_overall10](https://cloud.githubusercontent.com/assets/21995425/19003525/1bfc941a-8706-11e6-9fb2-eacd4dce398c.png)

**Comment by nagimov** [comment]
@savreline Let's not go crazy about calculating the temperature distribution along the wall as we discussed today, but simply calculate the heat flux through the wall assuming it has the thickness `b_w` and average conductance `k` calculated at average temperature `T` (e. g. calculated from `T_a` and `T_b` from previous time step). We can calculate the temperature distribution along the wall independently after calculating `T_a` and `T_b`, and gain some performance on the solver.

**Comment by savreline** [comment]
@nagimov Agreed, +is this what you were looking for?

![plot_overall10](https://cloud.githubusercontent.com/assets/21995425/19010292/bab7ec0e-8732-11e6-9ad8-56fd2c34ed90.png)

**Comment by nagimov** [comment]
@savreline yes, looking good. Closing the issue
