### ISSUE TITLE
Introduce limited heat conductance of the wall

### ISSUE THREAD

**Issue by nagimov** [nagimov/cyclotron-cryopanel#18]
We have decided to go with a simplified overall heat flux through the wall first, and use simplified (linear?) temperature distribution across the wall for calculations at each timestep

**Comment by savreline** [comment]
Set up of energy balances for this case 

[Energy_balance.pdf](https://github.com/nagimov/cyclotron-cryopanel/files/507356/Energy_balance.pdf)

**Comment by savreline** [comment]
Solution just barely converges for the case of 1 wall section... see plot
Doesn't converge for > 1 wall section. 

![plot_overall10](https://cloud.githubusercontent.com/assets/21995425/19133788/043f9734-8b0f-11e6-8645-13e9cf561a75.png)

**Comment by savreline** [comment]
LaTeX file with equations is updated 

[EnergyBalance2.pdf](https://github.com/nagimov/cyclotron-cryopanel/files/512544/EnergyBalance2.pdf)

**Comment by savreline** [comment]
@nagimov There is actually a much easier way to tackle all of this. Since we have an explicit `dTw_dt` and all unknowns are `Tw` we can just use `ode45` for the `T` solver. And that shouldn't have those stupid convergence issues!!

**Comment by nagimov** [comment]
@savreline how come it's explicit? We have not only `dTw/dt` but also `dTw/dz`, is that still feedable into ode45?

**Comment by savreline** [comment]
@nagimov Yes! Because `ode45` integrates in time, not space. The `dTw/dz` in the wall can be treated like `dT/dx` was in the streams. And we used `ode45` for the streams before we had to use `du/dt` which is implicit in `T`.

**Comment by savreline** [comment]
@nagimov Well `dTw(i)/dt = k/b_x*(2*Tw(i)-Tw(i+1)-Tw(i-1))/m*cp(Tw(i))` ... there is an explicit function between `dTw/dt` and `Tw`.

**Comment by nagimov** [comment]
@savreline sure! and we totally need a simple chart explaining which equations are solved each step (I'm lost already)

**Comment by savreline** [comment]
@nagimov Will work on it!

**Comment by savreline** [comment]
@nagimov Bam! If you use `HX_slices = 20` (before it was 10)

![plot_overall20](https://cloud.githubusercontent.com/assets/21995425/19209669/26436a98-8cc4-11e6-9bd9-126401175b5b.png)
 works much better!

**Comment by nagimov** [comment]
@savreline that is super-weird

**Comment by savreline** [comment]
Some 3D plots 

![3dplot_autumn](https://cloud.githubusercontent.com/assets/21995425/19289470/caa5e798-8fbf-11e6-8613-a8bf403a51c9.jpg)
![3dplot_hsv](https://cloud.githubusercontent.com/assets/21995425/19289473/ccf2479e-8fbf-11e6-9fcc-427cbb20df5c.jpg)

**Comment by savreline** [comment]
Fixed the code that uses only `fsolve`. The solution from that code is now the same as the `ode45` solution. So something is wrong with the equations, need to check.

**Comment by savreline** [comment]
Plots for a 2-phase Helium stream 

![plot_overall20](https://cloud.githubusercontent.com/assets/21995425/19331590/6ec6c218-909a-11e6-9feb-591b20263ffe.png)
![plot_n220](https://cloud.githubusercontent.com/assets/21995425/19331595/73bb185a-909a-11e6-9133-a70164cbb46a.png)

**Comment by savreline** [comment]
50 time steps

![plot_overall20](https://cloud.githubusercontent.com/assets/21995425/19405537/535e45a2-922d-11e6-93b0-9b4edc5ab8d2.png)

**Comment by savreline** [comment]
Updated

![plot_wall20](https://cloud.githubusercontent.com/assets/21995425/19533449/a613c87e-95f4-11e6-9cf9-294ed45016fa.png)
![3dplot](https://cloud.githubusercontent.com/assets/21995425/19533440/a1ee9eae-95f4-11e6-9308-6b7aac46c4cb.jpg)

**Comment by savreline** [comment]
Even better for 50 time steps 

![plot_wall20](https://cloud.githubusercontent.com/assets/21995425/19533810/248ed300-95f6-11e6-8d20-d26d0023b2b9.png)
![3dplot_50](https://cloud.githubusercontent.com/assets/21995425/19533806/22375a96-95f6-11e6-8fc4-d6c024c9c186.jpg)
![plot_overall20](https://cloud.githubusercontent.com/assets/21995425/19533801/1e4fea88-95f6-11e6-89bc-1c8262a13ad8.png)

**Comment by savreline** [comment]
Low temperature solution

![plot_he20](https://cloud.githubusercontent.com/assets/21995425/19538121/7b3e7bae-9607-11e6-94fc-2c78e8e67b22.png)
![plot_n220](https://cloud.githubusercontent.com/assets/21995425/19538124/7f7143a0-9607-11e6-8d48-e8bdabc5fbf4.png)
![plot_overall20](https://cloud.githubusercontent.com/assets/21995425/19538129/83a89932-9607-11e6-890b-5f1e8e90e0a5.png)
![plot_wall20](https://cloud.githubusercontent.com/assets/21995425/19538139/8df1317e-9607-11e6-937f-196a7d47bd97.png)
![3dplot_lowt](https://cloud.githubusercontent.com/assets/21995425/19538148/9b4b46a2-9607-11e6-83d2-dc7242599fdf.jpg)

**Comment by nagimov** [comment]
done, closing
