### ISSUE TITLE
create a simple case for heat exchanger with 4 flows

### ISSUE THREAD

**Issue by nagimov** [nagimov/cyclotron-cryopanel#2]
Extend two-flows case #1 for 4 flows with same initial data, initial conditions and results format

Streams schematic

```
a_in  ------------>----------- a_out
b_in  ------------>----------- b_out
c_out ------------<----------- c_in
d_out ------------<----------- d_in
```

`UA = const` for every pair of flows

**Comment by nagimov** [comment]
to be done after finishing 2-flow configuration

**Comment by nagimov** [comment]
to be reopened

**Comment by savreline** [comment]
@nagimov Got the code to solve both sides of the cryopanel. One side of the cryopanel is 200-150-100 (N2, wall, He) and the other side is 100-75-50. This is done to distinguish between the two in the testing stages. Will link the streams later on.

![a-b](https://cloud.githubusercontent.com/assets/21995425/19665987/afe48940-99fc-11e6-9d95-f1e32bb45237.jpg)
![c-d](https://cloud.githubusercontent.com/assets/21995425/19665991/b426e75a-99fc-11e6-901b-588e2103563a.jpg)
![walls](https://cloud.githubusercontent.com/assets/21995425/19665995/b664e5e4-99fc-11e6-92c5-aacfb06ede25.jpg)

Will now work on adding more features (heat conduction between streams)

**Comment by nagimov** [comment]
done
