### ISSUE TITLE
Try working with CoolProp

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#20]
CoolProp installed as per instructions on their website; however, it doesn't work.

Will try again.

**Comment by nagimov** [comment]
I'll work on coolprop.

**Comment by savreline** [comment]
@nagimov Their sample code runs (which means CoolProp is installed). However, their sample code gives an error. 

![error](https://cloud.githubusercontent.com/assets/21995425/19049466/6b6ab710-895f-11e6-97fe-2945176ecd87.jpg)

**Comment by nagimov** [comment]
[Wiki](https://github.com/nagimov/cyclotron-cryopanel/wiki/How-to-use-CoolProp-from-within-MATLAB) is updated to include the manual for two ways of using CoolProp: wrapper and c-like code.

**Comment by savreline** [comment]
First version of wrappers that accept arrays are uploaded. Those wrappers are tested and do work, but do not catch many errors. To be improved on a daily basis.

**Comment by nagimov** [comment]
I will rewrite `props_...` functions using c-like wrappers later (added to projects). This one is done and closed
