### ISSUE TITLE
CoolProp: compare performances of c-like wrapper and "native" MATLAB wrapper

### ISSUE THREAD

**Issue by nagimov** [nagimov/cyclotron-cryopanel#25]

**Comment by nagimov** [comment]
C-like wrapper is ~100 times faster in comparison with native MATLAB wrapper giving exact same results. Execution times in seconds (MATLAB wrapper, then c-like wrapper) and total absolute error:

```
>> tester_m
    6.8247
    0.0665
delta =
   4.9552e-11
```

**We are definitely replacing MATLAB wrapper with the one tested.**

**Comment by savreline** [comment]
@nagimov  Difference between C-wrapper and Matlab wrapper 

For Helium
![cwrapperhe](https://cloud.githubusercontent.com/assets/21995425/19581436/ca40cccc-96e1-11e6-88ba-b27849b06632.jpg)

For Nitrogen
![cwrappern2](https://cloud.githubusercontent.com/assets/21995425/19581435/ca3dfbaa-96e1-11e6-9bbe-9ba661db39ae.jpg)
