### ISSUE TITLE
integrate REFPROP with MATLAB

### ISSUE THREAD

**Issue by nagimov** [nagimov/cyclotron-cryopanel#3]
Create a simple thermal properties calculator, calling REFPROP functions from within MATLAB environment (e.g. find density of helium at 300K and 1bar)

**Comment by nagimov** [comment]
@savreline please upload a simple code snippet to the `issue_03` branch

**Comment by savreline** [comment]
@nagimov sample code snippet uploaded to the `issue_03` branch
