### ISSUE TITLE
Dynamically compute U from fluid's properties 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#30]
@nagimov Those are the plots produced using Coolprop at  `1 atm` for `Pr, lambda, mu` as a function of `q`. Does that look reasonable? 

![q_vs_prlmu](https://cloud.githubusercontent.com/assets/21995425/19365592/5183b7a2-9148-11e6-962a-b75ceaf8fc45.png)

**Comment by savreline** [comment]
Updated plots 

![q_vs_prlmu](https://cloud.githubusercontent.com/assets/21995425/19395993/8cc23ac0-91f5-11e6-942c-6a43c238ca28.png)

**Comment by nagimov** [comment]
@savreline viscosity seems to be correct, here is the plot I found:
![2016-10-16 14_59_39-m9sol](https://cloud.githubusercontent.com/assets/3197765/19421250/3ff2ec5e-93b1-11e6-845b-fb93240d2b4c.png)
src: http://www.sciencedirect.com/science/article/pii/073519339500045Z (accessible from triumf LAN)

Also `lambda` and `cp` are expected to be linear. So `Prandtl` vs. `q` plot is okay.
Closing this one?

**Comment by savreline** [comment]
@nagimov Yes, we should close

**Comment by savreline** [comment]
Low temperature solution 

![plot_wall20](https://cloud.githubusercontent.com/assets/21995425/19540141/4a68f9f4-9612-11e6-98b0-35161392e571.png)
![plot_overall20](https://cloud.githubusercontent.com/assets/21995425/19540142/4e11c6a8-9612-11e6-9da8-9795bb285eb6.png)
![plot_n220](https://cloud.githubusercontent.com/assets/21995425/19540146/529e68c0-9612-11e6-9f34-1d7bceeeb1ba.png)
![plot_he20](https://cloud.githubusercontent.com/assets/21995425/19540149/567c0c40-9612-11e6-9efb-4763cacbb140.png)
