### ISSUE TITLE
Temperature distribution in "wall's tail" 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#31]

**Comment by savreline** [comment]
@nagimov This is really cool!!

Plots for the wall and wall tail profiles if `As` is everywhere `=1`
![plot_wall20](https://cloud.githubusercontent.com/assets/21995425/19498939/81174d54-9548-11e6-9aea-81e30c810622.png)
![plot_tail20](https://cloud.githubusercontent.com/assets/21995425/19498932/7e109e94-9548-11e6-8b38-6a1756367f35.png)

Plots for the wall and wall tail profiles if `As` in the wall tail is bumped up
![plot_wall20](https://cloud.githubusercontent.com/assets/21995425/19498892/3e0cc228-9548-11e6-8457-25c45fbc89dc.png)
![plot_tail20](https://cloud.githubusercontent.com/assets/21995425/19498886/369ddab8-9548-11e6-8014-ac65a27210ca.png)

**Comment by savreline** [comment]
@nagimov The wall is fixed!!! 

![plot_wall20](https://cloud.githubusercontent.com/assets/21995425/19530962/ca2c34a8-95ea-11e6-824a-33d85e2747ca.png)
![plot_tail20](https://cloud.githubusercontent.com/assets/21995425/19530964/cbd4d670-95ea-11e6-90d1-33e90f15884f.png)
![3dplot](https://cloud.githubusercontent.com/assets/21995425/19530970/cfdcb42c-95ea-11e6-85bc-b41c0aabc8eb.jpg)

**Comment by savreline** [comment]
Low T solution - effect of delta_p??

![plot_n220](https://cloud.githubusercontent.com/assets/21995425/19538678/0aa3ea3e-960a-11e6-9598-82badc384ce8.png)
![plot_he20](https://cloud.githubusercontent.com/assets/21995425/19538679/0ab76cd0-960a-11e6-89c1-92e42e54fa65.png)
![3dplot_lowt](https://cloud.githubusercontent.com/assets/21995425/19538711/34340aaa-960a-11e6-9447-1f3c3286caaf.jpg)
![plot_wall20](https://cloud.githubusercontent.com/assets/21995425/19538929/4d559fd4-960b-11e6-98f0-1f4036c0263d.png)

**Comment by nagimov** [comment]
done and verified, closing
