### ISSUE TITLE
Add conductive heat transfer to simple 4-flow model 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#32]

**Comment by savreline** [comment]
@nagimov DONE! All of conduction and most of radiation has been added to the 4-stream model. See below for plots of walls and streams. Streams A and D have almost no change in temperature (as it should be the case, as there is both a + and - flux in/out of those streams, which cancels out). Walls A-C and B-D show only conduction & radiation. Walls A-B and C-D also show the "tail behavior". 

![streamlayout](https://cloud.githubusercontent.com/assets/21995425/19698344/c32a3cd2-9aa3-11e6-9dce-8886b621c5f4.jpg)
![streamab](https://cloud.githubusercontent.com/assets/21995425/19698347/c33285a4-9aa3-11e6-9975-2d6413267239.jpg)
![streamscd](https://cloud.githubusercontent.com/assets/21995425/19698345/c32e2ac2-9aa3-11e6-97c1-cab9d312b561.jpg)
![walls](https://cloud.githubusercontent.com/assets/21995425/19698346/c32f541a-9aa3-11e6-9de9-b29f8b41c6ee.jpg)
![streams](https://cloud.githubusercontent.com/assets/21995425/19698343/c32a2562-9aa3-11e6-9006-4d86613b0c10.jpg)

**Comment by savreline** [comment]
@nagimov Will work on improving the code, doing additional tests and adding more radiation heat transfer.

**Comment by savreline** [comment]
Solution time is ~2.5 minutes for the 4-streams, 20 HX_slices, 100 wall slices (in total) and 20 time steps.

**Comment by savreline** [comment]
Model works for phase change - here are a few examples 

![phasechange2](https://cloud.githubusercontent.com/assets/21995425/19703721/b4f1d5ce-9ab9-11e6-8880-7d5476d546b8.jpg)
![phasechange1](https://cloud.githubusercontent.com/assets/21995425/19703720/b4f1c462-9ab9-11e6-9e78-1ec7c6b04513.jpg)

The hump is due to radiation (if we remove radiation, no hump) 
![phasechange1wall](https://cloud.githubusercontent.com/assets/21995425/19703736/c2c488e0-9ab9-11e6-97e7-dc5d39ccd3b4.jpg)

**Comment by nagimov** [comment]
conductive is completed, closing
