### ISSUE TITLE
Add radiation heat transfer to simple 4-flow model 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#33]

**Comment by savreline** [comment]
@nagimov This is the model with **_all**_ radiation accounted for (He -> Every Wall Slice -> Ext). If we bump up the surface area we see that all He streams heat up and wall temperature goes down (especially in the higher temperature wall). Solution time goes up to 4.25 minutes. 

![streams_rad](https://cloud.githubusercontent.com/assets/21995425/19707710/041410b8-9ace-11e6-9f9e-6bf4428cae18.jpg)
![walls_rad](https://cloud.githubusercontent.com/assets/21995425/19707687/dde05050-9acd-11e6-8f23-fe745dc5010b.jpg)
![ab_rad](https://cloud.githubusercontent.com/assets/21995425/19707688/dde2b1ce-9acd-11e6-991f-da93cb1e3d56.jpg)
![cd_rad](https://cloud.githubusercontent.com/assets/21995425/19707689/dde53638-9acd-11e6-9885-4b8e74172225.jpg)

**Comment by savreline** [comment]
For comparison here is the solution without the He -> Wall part (only Wall -> Ext). 

![streams](https://cloud.githubusercontent.com/assets/21995425/19707769/6615372e-9ace-11e6-8db8-4d3e42a7e976.jpg)
![walls](https://cloud.githubusercontent.com/assets/21995425/19707771/661733a8-9ace-11e6-9de8-655befa55357.jpg)
![ab](https://cloud.githubusercontent.com/assets/21995425/19707772/6617469a-9ace-11e6-9e1a-6b198281b4f4.jpg)
![cd](https://cloud.githubusercontent.com/assets/21995425/19707770/66173fe2-9ace-11e6-87a5-0b010f10bb48.jpg)

**Comment by savreline** [comment]
Pressure drop plots

![streamspressuredrop](https://cloud.githubusercontent.com/assets/21995425/19744114/e83c043c-9b80-11e6-8aea-68ef4078e8bf.jpg)

**Comment by savreline** [comment]
Pressure drop plots with saturation effect 

![streamssatsol_norad](https://cloud.githubusercontent.com/assets/21995425/19744140/035d9af0-9b81-11e6-8f5b-2789f3fcebd4.jpg)

**Comment by nagimov** [comment]
done, closing
