### ISSUE TITLE
Link 4-stream model 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#34]
Link pairs of streams in a co-current and counter-current arrangements

**Comment by savreline** [comment]
@nagimov Linked streams, counter-current solution 

![streams](https://cloud.githubusercontent.com/assets/21995425/19816588/d6a41a98-9cfc-11e6-8148-70805c11735e.jpg)
![walls](https://cloud.githubusercontent.com/assets/21995425/19816590/d6a6106e-9cfc-11e6-989d-f2f511efbb53.jpg)
![streamacpressure](https://cloud.githubusercontent.com/assets/21995425/19816591/d6a7aa14-9cfc-11e6-8e5d-31b88389482c.jpg)
![streambdpressure](https://cloud.githubusercontent.com/assets/21995425/19816589/d6a48db6-9cfc-11e6-8c32-c63038c9f348.jpg)

**Comment by savreline** [comment]
@nagimov Linked streams, with co-current solution 

![streams](https://cloud.githubusercontent.com/assets/21995425/19816705/38be6c10-9cfd-11e6-9b2b-c3c44d5c0c01.jpg)

**Comment by nagimov** [comment]
done, linked
