### ISSUE TITLE
Get Cp from refprop as a function of T

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#5]
Same assumption as in issue 1, just removing assumption that `Cp` is constant. 

Get `Cp` from refprop `f(T)`

**Comment by savreline** [comment]
Code uploaded. Refprop works for `Cp` but reaches limit for nitrogen at below 63K due to limitations in the equation of state. Help says need to edit refprop file and pick a different equation of state. Not really an issue right now, will just keep the program above 63K.

**Comment by savreline** [comment]
In refprop quality is set to 0, as we are dealing with one-phase liquid streams for now. This becomes a problem if He is above critical point (5.3K). Will address later, so far will just stay below 5.3K

**Comment by savreline** [comment]
Figures 
<img src="https://cloud.githubusercontent.com/assets/21995425/18329642/626657ba-7509-11e6-97a6-21e408acab89.png" width=150px><img src="https://cloud.githubusercontent.com/assets/21995425/18329641/6265f09a-7509-11e6-9cff-f97d27eac7d6.png" width=150px>

**Comment by nagimov** [comment]
branch renamed to `issue_05`

**Comment by savreline** [comment]
Ah yeah my mistake, thanks!

**Comment by nagimov** [comment]
@savreline also let's do some housekeeping on our images here.
After you're done with uploading your image, convert the original image's code to html, so it looks tidier.
E.g.
original `![plot_t_vs_length](https://cloud.githubusercontent.com/assets/21995425/18329641/6265f09a-7509-11e6-9cff-f97d27eac7d6.png)` will become `<img src="https://cloud.githubusercontent.com/assets/21995425/18329641/6265f09a-7509-11e6-9cff-f97d27eac7d6.png" width=150px>`

**Comment by nagimov** [comment]
@savreline just a nitpick - let's for future revision specify mass flow (not volumetric flow)

**Comment by savreline** [comment]
Code is updated using `mid` and `last` for indices which makes indices much easier to read and figure out what is going on.

**Comment by savreline** [comment]
@nagimov Changing to mass flow would be more _natural_ once we get enthalpy in, just my opinion

**Comment by savreline** [comment]
[Link](http://www.boulder.nist.gov/div838/theory/refprop/FAQ2.htm) to discussion about equation of state limits in refprop and how to modify them

**Comment by nagimov** [comment]
@savreline that's a dangerous zone, let's not do that. If we go below the limits, something is wrong in either initial state or the code. For now just keep things away from the limits

**Comment by savreline** [comment]
The limit is 63K for nitrogen... so as long as nitrogen doesn't cool below 63K in the cyclotron in real life, we are good.

**Comment by nagimov** [comment]
@savreline Temperature in the LN2 circuit of the cyclotron doesn't go below 77.4K. Added to a meeting todo for discussion.
