### ISSUE TITLE
Remove the one-phase assumption 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#8]
Introducing equations in terms of quality, enthalpy and internal energy.

**Comment by savreline** [comment]
This will probably require some research since I'm not sure if `ode45` would work here. Need to examine in detail.

**Comment by savreline** [comment]
Yeah we no longer have an **_explicit**_ problem. We have an **_implicit**_ problem, so we have to use some **_implicit solver**_ like `ode15i`. Could take a while to set up and got to hope for the best it would work!

**Comment by savreline** [comment]
@nagimov Tomorrow morning I will work on setting up 'ode15i' and see how it goes. If it works and you like it, we can keep it. If not, we can get your method working. Or get it working regardless, but I would like to try `ode15i` first.

**Comment by savreline** [comment]
@nagimov I don't think the `ode15i` method would work here, because `dT/dt` is not even present. I'm setting up your finite difference method right now. When I finish the finite differences, if I get new ideas about `ode15i` I will try it again.

**Comment by savreline** [comment]
First version of code uploaded. Contains constant HX_UA assumption, but that should be easy to remove.

**Comment by nagimov** [comment]
Awesome. Let's test the consistency of this solution with ode45

**Comment by savreline** [comment]
Assumption of constant HX_UA is removed, some minor housekeeping done. But the numbers don't look that good (didn't look that good either when HX_UA was constant). Perhaps we should check to see if the initial data makes sense, etc.

**Comment by savreline** [comment]
Essentially `fsolve` in MATLAB is an iterative procedure and produces a bad solution. The iterative method doesn't seem to wanna do much work - produces a solution not far away from the initial guess. Or doesn't find a solution. Somehow got to make it put more effort into looking for a solution.

**Comment by savreline** [comment]
The most realistic solution so far 

<img src="https://cloud.githubusercontent.com/assets/21995425/18370418/b98a28ae-75e1-11e6-901b-d4d41e9e6d3a.jpg" width=150px>

**Comment by savreline** [comment]
Current ideas on how to proceed are summarized in the LaTeX document 

[fsolve_issues_Sept9.pdf](https://github.com/nagimov/cyclotron-cryopanel/files/464501/fsolve_issues_Sept9.pdf)

**Comment by savreline** [comment]
Added list of relevant MATLAB solvers to the .md file. 

So far tried `fminsearch`, code works, but hangs up on refprop going into the wrong area. 

If we want to change refprop limits (something for us to discuss), you need to do it (i.e. admin permission)

**Comment by savreline** [comment]
Will study different options for `fsolve` and there is a choice of solvers within `fsolve` to use, will go through those.

**Comment by savreline** [comment]
The _levenberg-marquardt_ solver of `fsolve` also hangs up on refprop limits. 

To try:
1. Use constrained solution function `fmincon` and set temperature limits as constraints as per refprop EOS constraints.  
2. Use polynomial approximations to refprop. 

LaTex file updated [fsolve_issues_Sept9_v2.pdf](https://github.com/nagimov/cyclotron-cryopanel/files/464767/fsolve_issues_Sept9_v2.pdf)

**Comment by savreline** [comment]
No. 1 from above is done. 

Code uploaded that uses `fmincon`, subject to constraints to avoid running into refprop limits. Perhaps I like this better as it doesn't require us to modify refprop files!!

**Comment by nagimov** [comment]
@savreline okay I got what you're doing wrong. You're solving the entire `F` matrix using `fsolve` (or any other solver) instead of finding the solution for each time step independently (i.e. solving it row by row). That complicates the problem significantly (think about solving that for t = 1000 hours, that'll be a zillion equation). We should only solve equations which are relevant to the current time step at each iteration.

**Comment by savreline** [comment]
@nagimov Yes of course!! I forgot that the time coordinate could be solved by steps, aggh! I was solving this like an `x` by `y` grid for the Laplace equation. Anyway I will work on the new code... I actually wrote code like this for the time problems before, will find it if need be. I will see if `fsolve` works better with new code and if not, then will try those other ideas we had. Thank you!

**Comment by nagimov** [comment]
@savreline I've done something with python and [COBYLA](https://en.wikipedia.org/wiki/COBYLA) solver. It works pretty good but takes long time to converge (I'm sure it's mostly because of python being slow).
Here is the evolution of enthalpy (at constant pressure) along HX for both streams
![figure_1](https://cloud.githubusercontent.com/assets/3197765/18569056/3bf7dbba-7b55-11e6-9bc2-8c960a644e61.png)
Took me only ~4 minutes to get this for 10 slices and 20 timesteps!

**Comment by savreline** [comment]
Very nice plot! Solution time looks promising!

**Comment by savreline** [comment]
@nagimov What time step did you use? Mine is 0.01s. 
What were your tolerances? Mine are 1e-9.

**Comment by nagimov** [comment]
@savreline 

```
tol = 1e-7
t_delta = 0.1  # integration time step, s
```

doesn't really matter while solution is converging though

**Comment by savreline** [comment]
Even through the solution converges very well (`fval` < 1e-6) I'm very suspicious of the plots. They reach steady-state way too fast and sometimes there are oscillations at the beginning. 

<img src="https://cloud.githubusercontent.com/assets/21995425/18854495/bc544d1c-8400-11e6-9d8b-82c3e69c9ba4.png" width=150px>
<img src="https://cloud.githubusercontent.com/assets/21995425/18854499/ca43c038-8400-11e6-89ca-81715daa9312.png" width=150px>
<img src="https://cloud.githubusercontent.com/assets/21995425/18854503/cdf483de-8400-11e6-8cf5-f5b5bc629b89.png" width=150px>

**Comment by savreline** [comment]
Will study the code to see what could be wrong

**Comment by savreline** [comment]
@nagimov We should close this issue as we are ahead of this step by now.

**Comment by savreline** [comment]
Plot for Helium with phase-change occurring after a few time steps 

![plot_n210](https://cloud.githubusercontent.com/assets/21995425/19083854/d8ebcf4a-8a18-11e6-95b9-c9dca4de4189.png)
![plot_overall10](https://cloud.githubusercontent.com/assets/21995425/19083860/dbc553c6-8a18-11e6-87c8-e116fb8e7284.png)

**Comment by savreline** [comment]
@nagimov Better?

![plot_n210](https://cloud.githubusercontent.com/assets/21995425/19092082/011aead4-8a3a-11e6-88f0-c3ca9225db72.png)

**Comment by nagimov** [comment]
closing, done
