### ISSUE TITLE
refprop investigations and approximations 

### ISSUE THREAD

**Issue by savreline** [nagimov/cyclotron-cryopanel#9]
I. Find the function in refprop that determines quality of stream. 

_function not yet found - nothing in the help file or on the web_

II. Determine polynomial approximations to refprop functions (so that code doesn't call refprop all the time)

**Comment by savreline** [comment]
Turns out that in our range of temperatures:

H and U are 100% linear for nitrogen - we get an r2 value of 1.0000, so not issues fitting a line here.
H and U are almost linear for helium - we get an r2 value of .9984, so perhaps fitting a line is OK for now. We could also fit a second-order polynomial (parabola) and get an r2 value of .9999!!! 

<img src="https://cloud.githubusercontent.com/assets/21995425/18404791/9b438186-76a1-11e6-9473-bb8ad1ad2316.png" width=150px>

**Comment by nagimov** [comment]
@savreline 
- [ ] check the current version with the above approximations, post the results here
- [x] wrap something around refprop and catch calls outside of allowed property regions to avoid exceptions
- [ ] check the formulations using simple case with ~2-3 slices and solving the system of equations manually (e.g. in excel)

Ultimately we want to have `fsolve` working fine with our equation at least for the easiest cases (low `UA`)

**Comment by savreline** [comment]
Refrprop wrapper created, works well.

**Comment by savreline** [comment]
Wrapper updated, reads error messages

**Comment by nagimov** [comment]
+1 for a nice regexp parser :)

**Comment by savreline** [comment]
@nagimov Matlab website says that all solvers like `fsolve` only **always** find a local minimum. They list procedures from global optimization toolbox on how to find global minimums.

**Comment by savreline** [comment]
1. Tried global minimum search algorithms - they fail. 
   They mainly fail because `fmincon` fails on this problem for some reason.
2. Tried to linearize refprop - r2 are good (almost a straight line for H-T and H-U at constant P).
   The model solves way faster (~11s).
   But the solution is still bad. Code uploaded under issue_09. 

Conclusion: need to check the model going further.

**Comment by nagimov** [comment]
We're done with refprop and switched to coolprop for performance.
